import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import type { BusManifest, BusTypeEntry } from "./manifest.js";

const HEADER = `/**
 * Auto-generated by chowbea-axios Type Bus.
 * DO NOT EDIT MANUALLY - your changes will be overwritten.
 */
`;

function moduleName(barrelKey: string): string {
	return barrelKey.replace(/\//g, ".");
}

function renderBarrelFile(barrelKey: string, entries: BusTypeEntry[]): string {
	const blocks = entries.map(
		(e) => `/** From ${e.source}:${e.line} */\n${e.declaration}`,
	);
	return `${HEADER}\n${blocks.join("\n\n")}\n`;
}

export function renderBusFiles(manifest: BusManifest): Record<string, string> {
	const files: Record<string, string> = {};
	const keysByFilename: Record<string, string> = {};
	const keys = Object.keys(manifest.barrels).sort();
	for (const key of keys) {
		const filename = `${moduleName(key)}.ts`;
		if (filename === "index.ts") {
			throw new Error(
				`Bus emission filename collision: "index.ts" reserved for the generated re-export index, ` +
					`but barrel key "index" would produce it. Rename the barrel.`,
			);
		}
		if (keysByFilename[filename]) {
			throw new Error(
				`Bus emission filename collision: "${filename}" produced by both "${keysByFilename[filename]}" and "${key}". ` +
					`Barrel keys must flatten distinctly.`,
			);
		}
		keysByFilename[filename] = key;
		files[filename] = renderBarrelFile(key, manifest.barrels[key]);
	}
	const reexports = keys.map((k) => `export * from "./${moduleName(k)}";`);
	files["index.ts"] = `${HEADER}\n${reexports.join("\n")}\n`;
	return files;
}

/** The bus dir is always-overwritten territory: wipe, then write. */
export async function writeBusFiles(manifest: BusManifest, busDir: string): Promise<string[]> {
	await rm(busDir, { recursive: true, force: true });
	await mkdir(busDir, { recursive: true });
	const files = renderBusFiles(manifest);
	const written: string[] = [];
	for (const [name, content] of Object.entries(files)) {
		const full = path.join(busDir, name);
		await writeFile(full, content, "utf8");
		written.push(full);
	}
	return written;
}
